deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kgolani@andrew.cmu.edu
  password:
    secure: hgM8PQMKrb9cysqednUGz7zjqTUhVOPmMkaTOZtDr51YBUrV7cia86LNyhU1BtMFfEK5IZ+Q6rw4DpyC6IdBft7x77PU/HxebWIKRClcvejiDaMsycrsgQrzkr3iTQWm0dV/ki2/UlvbGnjJP7cdfGkrQQqNxAbCZzw7XRSaB+9DhqQ2YtlRDG5IzFKdxFEMP6VxHfpUWhJaPrdmgMcRN9ElJoUzCcQWIQsIOpIsce7xRJY2vHofc+pLn7/e3DPbL9xnGLRoNGWgKdtcG+WiZsoTQtpUalHiS5OfQrAZFbYhRiG6Czgk4KhsQ6NgrYG2CzVxaYbVlc+sy67WRoR27Gx0o+yFeqKQq5ssULGySswk+2WA44imO68CzNReA98XysXGnneSa8llWjkHrMg5KFZeezvBSaORsCrxB8AzSvU7RB2ZT7NaAIh4eWcJoxz6fqysX89BMvk/QQEkvDeaETwTt9Mkuwf9yvWdZqdxvAZIFZi6c+MuijRQ8TZwVeVWtJCjvqRkhqItwwBkB+UwAVuZdtFmr/9zDbhgFqpk5brtKV8kFc2OtMGBowQegS30VhihNVX9wTcZCvIc6fi/EbyyTDpiDS1dYoSAsXnzRCfuaSFz4yDSNj0KEWlnCkbZYfneQtb57YFE5rDMIqrReY7Khl6RynPICUD/JoRs+P4=
  organization: kgolani-org
  space: development
  on:
    repo: superboyknx/ImageGalleryApp
