language: java
jdk:
  - oraclejdk8
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kgolani@andrew.cmu.edu
  password:
    secure: VxiVwqrvreiaoQsxfYa9m4ZDZr8qDqa5Wp2tZMI5VgsIsIcQ0aWAGAtLpPdOXcv1Ds8QKZ26tzNCgG74QBhkaVbqw1dUOobALiN8qRMtHj89axQj09ieYw3826Z2u1+GjIfSMVV2WOs6F6OxxzS3frCmuAoviqpfPZVyGzCSXtvR/4UVjFyRBqeXkavXPC5F7S+OIV8PFJdd4W/aJLnviu5G5Xeov9Y3WFeUlPwFY7styt/JS7WU7AFzffT+Yxnpl408H8vhzsKxinvQxXdVsOGaHYKvQ7K+ggo5YfkNTZOpzABh4bAuMc5pbl9vNdXPLsVrQgt2zYvZUTmPVkJO3T7QTkMoUPWlKvzTaInAzR+XyLLUe7dadEwR2Sr3yLyKRZAp3LC3S039yl+s01oNZkvSs+KF/nJB5fWvr+MiW/BBe7sVcoCWQJMCyxZZpoc8zzcSJEyvRhKGuWRNQfiQghkhh8MTz1yewFG4fL7EMrWBZKx5PXgLxWG25fnZrZ5lCDxHOafMxPTiKExnQJji0/Tipp7yvoPqJ0SDgzGjwolR0cW8tCq+3RaupIYRD6euGQzLcJUfoQYIlBMNvm9nORV/AMnquxmxzw4e5TGZk0jc4y7Vzi9uh6+b+RG75UJMUeIiLfue9loBCmUZCLgSdf4nscLeyAvIXOSrQwSLMts=
  organization: kgolani-org
  space: development
  on:
    repo: superboyknx/ImageGalleryApp
