language: java
jdk:
- oraclejdk8
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kgolani@andrew.cmu.edu
  password:
    secure: SM02mVT+NXFzMQ0jxRQLQ3CCHKfVItTq/uJShMwNV+sa75MOHnhA/Npr1GNpxbMZQ0XeunnmOtFzQx2yUADmLNpsS6cDQ0Q24K848yb0JvwSfSNqLC6IwHgVrd12Df4V/DqJP0wnHVD8CeQ9E+5MNFdbJeSy4CrqBJ4a+qe7jckbP98q/8Bx2TT5d1jENPSFCpdfgXx7Kw51ctfo/yUe832KdZTAXCgvUQzbMRA0Qos6V7EmL5Qg3S6Qiuc7P6PLy1FgWrKrSzw3FGDjs//BLoqVrxu9CdQ54KTIw0CIAc6UQ+xfiyF8R9ERD1uvREq1UbEsF871bCGWM6Iwfh9L70X+8kZZfaKcSKhWP9BZNT8QjR0uHD6f5PB2BYanZJWvwMx85oE3McvWERJ47JB58BcenVfIChD2hOTYbewaz7sUsgoBxvCrz2eu9HDyo+lo6JW9Nd++ti8QHcQtytut15Gm7rw76Y28ijl7bZJVyivJWnuHdwyR2GZqVGb0ZE7snRH1g75gSOZeiAaDMoPBdCwEUIBuNLwMtW4DaajEce9tjgJojOafVYrKKfqP4E0ReaDADRPFaqd8RhT8DqzgEWxqnNGuxyGLXnHWFFLBfZ+xxeaY3LIfEmXcNg9R9OA64Q7Gx/AZzpM39AmE3+f8tSn8k6ntHDrK+WH/GIfZBbk=
  organization: kgolani-org
  space: development
  on:
    repo: superboyknx/ImageGalleryApp
